new parameter for drush from Vendor directory
Added new Parameter -v to indicate to use Vendor parameter
If -v is added as parameter /../vendor/drush/drush/drush is added to the path
default for DRUSH is then <drupal root>/../vendor/drush/drush/drush

Only problem: could not get it to run with --config param. There was an error while checking is_drupal_root_dir. Therefore I just moved that setting to after this check. 

`[preflight] Unable to parse at line 1 (near "<?php").``

diff --git a/bin/check_drupal b/bin/check_drupal
--- a/bin/check_drupal
+++ b/bin/check_drupal
@@ -201,7 +201,7 @@ is_drupal_root() {
 	fi
 
 	# Use drush to test root
-	if ! drush -r "${1}" --uri="${2}" status | grep 'Drupal root' 1>/dev/null; then
+	if ! "${DRUSH}" -r "${1}" --uri="${2}" status | grep 'Drupal root' 1>/dev/null; then
 		return 1
 	fi
 	return 0
@@ -522,7 +522,7 @@ print_version() {
 # @output string  The requirements.
 # @return integer 0 on success, 2 on fail
 check() {
-	if command -v drush > /dev/null 2>&1; then
+	if command -v {$DRUSH} > /dev/null 2>&1; then
 		echo "[OK] drush found"
 		return "$EXIT_ERR"
 	else
@@ -535,7 +535,7 @@ check() {
 # @output string  The usage screen.
 # @return integer 0
 print_usage() {
-	printf "Usage: %s -d <drupal root> [-n <name>] [-s <w|e>] [-u <w|e>] [-e <w|e>] [-w <w|e>] [-m <w|e>] [-i <uri>] [-l <log file>] [-r]\n" "${INFO_NAME}"
+	printf "Usage: %s -d <drupal root> [-n <name>] [-s <w|e>] [-u <w|e>] [-e <w|e>] [-w <w|e>] [-m <w|e>] [-i <uri>] [-l <log file>] [-r]\n  [-v]\n" "${INFO_NAME}"
 	printf "OR     %s --check\n" "${INFO_NAME}"
 	printf "OR     %s --help\n" "${INFO_NAME}"
 	printf "OR     %s --version\n\n" "${INFO_NAME}"
@@ -612,6 +612,9 @@ print_help() {
 	printf "  -r                     [optional] Filters all updates that are locked via drush.\n"
 	printf "                         For general infos about locking run 'drush pm-updatestatus -h'\n\n"
 
+	printf "  -v                     [optional] Use Vendor Drush instead of global drush.\n"
+	printf "                         default for <drupal root>/../vendor/drush/drush/drush '\n\n"
+
 	printf "  --check                Check for program requirements.\n"
 	printf "  --help                 Show this help\n"
 	printf "  --version              Show version information.\n"
@@ -648,7 +651,7 @@ fi
 ############################################################
 
 # Do we have 'drush'?
-if ! command -v drush > /dev/null 2>&1 ; then
+if ! command -v ${DRUSH} > /dev/null 2>&1 ; then
 	printf "[UNKNOWN] 'drush' not found.\n"
 	exit $EXIT_UNKNOWN
 fi
@@ -769,6 +772,11 @@ while test -n "$1"; do
 		-r)
 			LOCK="1"
 			;;
+		-v)
+			VENDOR_DRUSH="1"
+			VENDOR_DRUSH_PATH="../vendor/drush/drush/drush"
+			DRUSH="${DRUPAL_ROOT}/${VENDOR_DRUSH_PATH}"
+			;;
 		*)
 			printf "Unknown argument: %s\n" "$1"
 			print_usage
@@ -777,15 +785,6 @@ while test -n "$1"; do
 	esac
 	shift
 done
-
-# Use a drushrc.php file to set the language to english
-if ! DRUSHRC="$(write_drushrc)"; then
-	printf "[UNKNOWN] Unable to create tmpfile\n"
-	exit $EXIT_UNKNOWN
-fi
-
-DRUSH="${DRUSH} --config=${DRUSHRC}"
-
 
 ############################################################
 # Validate arguments
@@ -822,6 +821,16 @@ if [ -n "$LOGGING" ]; then
 		fi
 	fi
 fi
+
+
+# Use a drushrc.php file to set the language to english
+if ! DRUSHRC="$(write_drushrc)"; then
+	printf "[UNKNOWN] Unable to create tmpfile\n"
+	exit $EXIT_UNKNOWN
+fi
+
+DRUSH="${DRUSH} --config=${DRUSHRC}"
+
 
 
 ############################################################
