Adding checking Watchdog logs for critical or higher messages

diff --git a/bin/check_drupal b/bin/check_drupal
--- a/bin/check_drupal
+++ b/bin/check_drupal
@@ -547,6 +547,42 @@ check_cron() {
 
 }
 
+# Check Drupal Watchdog logs for messages of severity CRITICAL or higher.
+#
+# @param  string  Path to Drupal root.
+# @param  string  Drupal multisite URI
+# @output string  Drupal Watchdog messages.
+# @return integer Nagios exit code.
+check_watchdog() {
+
+        _drupal_root="${1}"
+        _multisite_uri="${2}"
+
+        # read watchdog logs
+        # No URI specified (single site)
+        if [ -z "${_multisite_uri}" ]; then
+                _watchdog_="$(LC_MESSAGES=${LOCALE} ${DRUSH} --root="${_drupal_root}" watchdog-show --severity=0 --severity=1 --severity=2 --no-field-labels 2>/dev/null)"
+                _ret=$?
+        else
+                _watchdog="$(LC_MESSAGES=${LOCALE} ${DRUSH} --root="${_drupal_root}" --uri="${_multisite_uri}" watchdog-show --severity=0 --severity=1 --severity=2 --no-field-labels 2>/dev/null)"
+                _ret=$?
+        fi
+
+        # Error might have multiple causes...
+        # Drupal database not connected?
+        # Drupal root wrong?
+        if [ ${_ret} -ne 0 ]; then
+                return $EXIT_UNKNOWN
+        fi
+
+	if [(echo ${_watchdog} | grep "No log messages available" | wc -l) -eq 1]; then
+		echo "[OK] No Watchdog messages of severity CRITICAL or higher"
+		return $EXIT_OK
+	else
+		echo "${_watchdog}"
+		return $EXIT_ERR
+	fi
+}
 
 ############################################################
 # Program Functions
@@ -716,6 +752,7 @@ MSG_CORE_ERROR=""
 MSG_CORE_WARNING=""
 MSG_DB_UPDATE=""
 MSG_CRON=""
+MSG_WATCHDOG=""
 
 # Info for normal Status message if there is an error/warning
 CNT_SECURITY_UPDATE_ERROR="0"
@@ -724,6 +761,7 @@ CNT_CORE_ERR_ERROR="0"
 CNT_CORE_WARN_ERROR="0"
 CNT_DB_UPDATE_ERROR="0"
 CNT_CRON_ERROR="0"
+CNT_WATCHDOG_ERROR="0"
 
 # Count warnings and errors for performance data
 CNT_ALL=0
@@ -809,6 +847,15 @@ while test -n "$1"; do
                                 exit $EXIT_UNKNOWN
                         fi   
                         ;;  
+                # ---- 9. Watchdog Logs
+                -g)
+                        # Get next arg in list (Severity <w|e>)
+                        shift
+                        if ! CHECK_G="$(get_severity "$1")" > /dev/null 2>&1; then
+                                echo "Invalid value \"$1\" for option \"-g\"."
+                                exit $EXIT_UNKNOWN
+                        fi
+                        ;;
 		# ---- 9. Do we have an URI for a multisite?
 		-i)
 			# Get next arg in list (URL)
@@ -1094,6 +1141,40 @@ if [ -n "$CHECK_C" ]; then
 fi
 
 
+#### 7. Check Drupal Watchdog logs for messages of severity CRITICAL or higher
+if [ -n "$CHECK_G" ]; then
+
+        SEVERITY="$CHECK_G"
+
+        # Execute Command
+        MSG_WATCHDOG="$(check_watchdog "${DRUPAL_ROOT}" "${MULTISITE_URI}")"
+        TMP_EXIT="$?"
+
+        # Merge exit codes
+        if [ "$TMP_EXIT" != "0" ]; then
+                # Count lines as number of issues
+                CNT_WATCHDOG_ERROR="$(echo "${MSG_WATCHDOG}" | wc -l | xargs)"
+
+                if [ "$SEVERITY" = "$EXIT_ERR" ]; then
+                        CNT_ERROR=$((CNT_ERROR+1))
+                        MSG_WATCHDOG="$(prepend_line "${MSG_WATCHDOG}" "[CRITICAL] ")"
+                        MSG_WATCHDOG="==== WATCHDOG ====\n${MSG_WATCHDOG}"
+                        NAGIOS_EXIT="$(merge_exit_codes "$NAGIOS_EXIT" "2")"
+                else
+                        CNT_WARNING=$((CNT_WARNING+1))
+                        MSG_WATCHDOG="$(prepend_line "${MSG_WATCHDOG}" "[WARNING] ")"
+                        MSG_WATCHDOG="==== WATCHDOG ====\n${MSG_WATCHDOG}"
+                        NAGIOS_EXIT="$(merge_exit_codes "$NAGIOS_EXIT" "1")"
+                fi
+        else
+                CNT_OK=$((CNT_OK+1))
+                MSG_WATCHDOG="==== WATCHDOG ====\n[OK] WATCHDOG ok"
+                NAGIOS_EXIT="$(merge_exit_codes "$NAGIOS_EXIT" "0")"
+        fi
+        CNT_ALL=$((CNT_ALL+1))
+
+fi
+
 
 ############################################################
 # Cleanup
@@ -1152,6 +1233,13 @@ if [ "$CNT_CRON_ERROR" != "0" ]; then
                 INFO="$(merge_text "${INFO}" "${CNT_CRON_ERROR} Cron warnings" ", ")"
         fi
 fi
+if [ "$CNT_WATCHDOG_ERROR" != "0" ]; then
+        if [ "$CNT_WATCHDOG_ERROR" = "1" ]; then
+                INFO="$(merge_text "${INFO}" "Watchdog logs" ", ")"
+        else
+                INFO="$(merge_text "${INFO}" "${CNT_WATCHDOG_ERROR} Watchdog logs" ", ")"
+        fi
+fi
 
 #### Short output (std status)
 OUTPUT=""
@@ -1176,6 +1264,8 @@ PERF="$(printf "%s'Core Errors'=%d;;;; "         "${PERF}" "${CNT_CORE_ERR_ERROR
 PERF="$(printf "%s'Core Warnings'=%d;;;; "       "${PERF}" "${CNT_CORE_WARN_ERROR}")"
 PERF="$(printf "%s'Database Migrations'=%d;;;; " "${PERF}" "${CNT_DB_UPDATE_ERROR}")"
 PERF="$(printf "%s'CRON'=%d;;;; " 		 "${PERF}" "${CNT_CRON_ERROR}")"
+PERF="$(printf "%s'Watchdog Logs'=%d;;;; "                "${PERF}" "${CNT_WATCHDOG_ERROR}")"
+
 
 PERF="$(printf "%s'OK'=%d;;;0;%d "        "${PERF}" "${CNT_OK}"      "${CNT_ALL}")"
 PERF="$(printf "%s'Errors'=%d;1;1;0;%d "  "${PERF}" "${CNT_ERROR}"   "${CNT_ALL}")"
@@ -1189,7 +1279,8 @@ if [ "$MSG_SYSTEM_UPDATE"   != "" ]; then E_OUTPUT="$(merge_text "${E_OUTPUT}" "
 if [ "$MSG_CORE_ERROR"      != "" ]; then E_OUTPUT="$(merge_text "${E_OUTPUT}" "${MSG_CORE_ERROR}" "\n")";      fi
 if [ "$MSG_CORE_WARNING"    != "" ]; then E_OUTPUT="$(merge_text "${E_OUTPUT}" "${MSG_CORE_WARNING}" "\n")";    fi
 if [ "$MSG_DB_UPDATE"       != "" ]; then E_OUTPUT="$(merge_text "${E_OUTPUT}" "${MSG_DB_UPDATE}" "\n")";       fi
-if [ "$MSG_CRON"	    != "" ]; then E_OUTPUT="$(merge_text "${E_OUTPUT}" "${MSG_CRON}" "\n")";       fi
+if [ "$MSG_CRON"	    != "" ]; then E_OUTPUT="$(merge_text "${E_OUTPUT}" "${MSG_CRON}" "\n")";            fi
+if [ "$MSG_WATCHDOG"        != "" ]; then E_OUTPUT="$(merge_text "${E_OUTPUT}" "${MSG_WATCHDOG}" "\n")";        fi
 
 
 #### Log to file?
